/**
 * Build step: turn a font into geometry.
 *
 *   pnpm extract --font <ttf|otf|woff|url> --out fonts/name.json
 *                [--chars ABC] [--name "Family 700"]
 *
 * Defaults to Familjen Grotesk 700 from Google Fonts, uppercase + digits,
 * which is what the wordmark needs. The extraction itself lives in
 * `src/extract.ts`, so the browser reads a dropped font the same way.
 */

import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { DEFAULT_CHARS, extractFont } from "../src/extract.ts";

const HERE = dirname(fileURLToPath(import.meta.url));

const DEFAULT_FONT =
  "https://fonts.gstatic.com/s/familjengrotesk/v11/Qw3LZR9ZHiDnImG6-NEMQ41wby8WRnYsfkunR_eGfMFubizt.ttf";

function args() {
  const out = {};
  for (let i = 2; i < process.argv.length; i += 2) {
    const key = process.argv[i].replace(/^--/, "");
    out[key] = process.argv[i + 1];
  }
  return out;
}

async function load(src) {
  if (/^https?:/.test(src)) {
    const res = await fetch(src, {
      // gstatic serves woff2 to modern UAs and truetype to older ones, and
      // opentype.js only parses the latter.
      headers: { "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_3)" },
    });
    if (!res.ok) throw new Error(`${res.status} fetching ${src}`);
    return Buffer.from(await res.arrayBuffer());
  }
  return readFileSync(resolve(src));
}

async function main() {
  const opts = args();
  const bytes = await load(opts.font ?? DEFAULT_FONT);
  const { font: data, missing } = extractFont(bytes.buffer.slice(bytes.byteOffset, bytes.byteOffset + bytes.byteLength), {
    chars: opts.chars ?? DEFAULT_CHARS,
    name: opts.name,
  });
  for (const ch of missing) console.warn(`no glyph for ${JSON.stringify(ch)} — skipped`);

  const out = resolve(HERE, "..", opts.out ?? "fonts/familjen-grotesk-700.json");
  mkdirSync(dirname(out), { recursive: true });
  const json = JSON.stringify(data);
  writeFileSync(out, json);

  /**
   * A typed twin of the JSON, so importing a font costs the compiler one
   * string literal instead of a structural type for 2,600 points — and costs
   * the browser one `JSON.parse`, which V8 runs faster than it builds the
   * equivalent object literal.
   */
  const stem = out.replace(/\.json$/, "");
  const ident = stem
    .split("/")
    .pop()
    .replace(/[^a-zA-Z0-9]+(.)/g, (_, c) => c.toUpperCase())
    .replace(/^[0-9]+/, "");
  writeFileSync(
    `${stem}.ts`,
    `// Generated by scripts/extract.mjs — do not edit.\n` +
      `// ${data.name}, ${Object.keys(data.glyphs).length} glyphs.\n` +
      `import type { GlyphFont } from "../src/types";\n\n` +
      `const ${ident} = JSON.parse(\n  ${JSON.stringify(json)},\n) as GlyphFont;\n\n` +
      `export default ${ident};\n`,
  );

  const pts = Object.values(data.glyphs).reduce(
    (n, g) => n + g.contours.reduce((m, c) => m + c.length, 0), 0,
  );
  console.log(
    `${data.name}: ${Object.keys(data.glyphs).length} glyphs, ${pts} points, ` +
      `${(json.length / 1024).toFixed(1)} kB -> ${out}`,
  );
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
